spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DATABASE_URL:localhost}:5432/${POSTGRES_DATABASE_NAME:core_banking}
    username: ${POSTGRES_DATABASE_USERNAME:postgres}
    password: ${POSTGRES_DATABASE_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
